server:
    port: 30405
    servlet:
        context-path: /apis
spring:
    kafka:
        bootstrap-servers: localhost:9092
        listener:
            missing-topics-fatal: false
            ack-mode: manual_immediate

noise:
    localusername: tuofengkeji
    localpassword: 1qaz@WSX3edc